name: TaspiaMines
version: '${version}'
main: com.taspia.taspiamines.TaspiaMines
api-version: '1.20'
load: STARTUP
depend: [WorldGuard, WorldEdit]
commands:
  taspiamines:
    description: Reloads the TaspiaMines configuration
    usage: /<command> reload
